#!/usr/bin/bash
showem ()
{
	set | grep -E 'BASH_LINENO|BASH_SOURCE|FUNCNAME' | grep -v set >&2
}

showem
set | grep -E 'BASH_LINENO|BASH_SOURCE|FUNCNAME' | grep -v set >&2


guts_func ()
{
    echo "in guts_func, caller is ${FUNCNAME[1]}"
    local iam=${FUNCNAME[0]}
    if [ -n "${FUNCNAME[1]}" ] && \
           [ ! "${FUNCNAME[1]}" = 'source' ] && \
           [ ! "${FUNCNAME[1]}" = 'main' ]
    then
        iam="${FUNCNAME[1]}"
    fi
    echo "'iam' is '$iam'"
}

wrap_func ()
{
    guts_func
}

guts_func
wrap_func
declare output
output=$(wrap_func)
echo "This is the output of wrap_func, but captured:"
echo "$output"
