#!/usr/bin/env bash

usage()
{
    pod2text "$0" | ${PAGER:cat}
}

:<<'__PODUSAGE__'
=head1 NAME

foo - script/command/function that does something

=head1 SYNOPSIS

 foo [--option1] [ --option2 optionarg ] arg1 [arg2 ...] \
     [fee] [dfsdfs] [sfsdfsf]

=head1 DESCRIPTION

Describe in general terms what foo does.

=head1 ARGUMENTS

=over 4

=item arg

Describe what arg does, should be, etc. Add a new =item for each distinct arg.

=back

=head1 OPTIONS

=over 4

=item --option1

Describe what --option1 does.

=item --option2

Describe what --option2 does. Describe what optionarg does.

=over 2

=item *

A choice for optionarg

=item *

Another choice for optionarg

=back

=back

=cut

__PODUSAGE__
