#!/usr/bin/env bash

### The short version:

declare usage_cmd="script-usage"
## If there's any chance that this will be in a script that will be dotted in,
## remove the explicit out_cmd calls.
declare out_cmd="exit"
declare moreopts=1
declare verbose=0
while [[ "$1" =~ ^- ]] && ((moreopts))
do
    declare original="$1"
    shift
    declare option
    option=$(dashstripper "$original")
    ## This bit deals with --foo=bar instead of --foo bar
    declare okey=''
    declare ovalue=''
    if [[ "$option" =~ = ]]
    then
        okey=${option%%=*}
        ovalue=${option#*=}
        option="$okey"
    fi

    case $option in

        ## Option with no arg
        noarg )
            ## Process the option.
            setsomething=1
            ;;

        ## Option with arg
        witharg )
            ## Copy the option's value if it was set from above via
            ## --opt=arg. If not, get it from the next script
            ## argument (--opt arg).
            witharg=${ovalue:-$1}

            ## If $ovalue is blank, we took arg from the next command line arg;
            ## need to shift it off.
            [ -z "$ovalue" ] && shift

            ## Continue processing option.
            ;;

        ## standard options
        h | help )
            $usage_cmd
            $out_cmd 0
            ;;
        verbose | v )
            #### A yes/no:
            verbose=1
            #### If a level, use instead:
            #### [ -z "$ovalue" ] && ovalue=$1 && shift
            ###  verbose="$ovalue"
            ;;

        ## Put your old option case entries in at this point.

        --)
            moreopts=0
            ;;
        * )
            cmd-echo -- "$original is an invalid option. See $0 --help"
            $out_cmd 1
            ;;
    esac
done

## The End, to make sure we never eval the usage statement
$out_cmd 0

## Go grab the usage template the file USAGE
